_core:
  default_config_hash: _0b2Dyb993JzkbRlFnYz7hMynhBxgPtAERPG2BDTudI
favicon:
  mimetype: image/png
  path: 'public://home.png'
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: 'public://construction.png'
  use_default: false
all_icons_show: 1
facebook_url: 'https://www.facebook.com/idewdot'
twitter_url: 'https://twitter.com/dewdots'
instagram_url: 'https://www.instagram.com/google'
linkedin_url: 'https://in.linkedin.com/company/google'
youtube_url: 'https://www.youtube.com/user/Google'
vimeo_url: 'https://vimeo.com/'
telegram_url: 'https://telegram.org/'
whatsapp_url: 'https://web.whatsapp.com/'
github_url: 'https://github.com/'
vk_url: ''
circle_type: circle_border
slider_show: 1
slider_code: "<li>\r\n  <h1>Aman Construction is <em>Multipurpose</em> Point</h1>\r\n  <p>Welcome to Aman Construction !!!</p>\r\n  <a class=\"button-link\" href=\"#\">Let Us Know</a>\r\n</li>\r\n<li>\r\n  <h1>Welcome To <em>Aman Construction</em> Design Studio</h1>\r\n  <p>We present you material design. We keep all materials into making our lovely home.</p>\r\n  <a class=\"button-link\" href=\"#\">Lovely Home</a>\r\n</li>\r\n<li>\r\n  <h1>We Provide <em>Awesome</em> Home designs, Suggestions, Material.</h1>\r\n  <p>We Provide of high quality, flexible and beautifully crafted that stand out of crowd.</p>\r\n  <a class=\"button-link\" href=\"#\">Let us know your Requirement</a>\r\n</li>"
slider_image:
  - '3'
slider_image_path: ''
front_sidebar: 0
comment_user_pic: 1
node_author_pic: 0
node_tags: 0
font_icon_fontawesome: 1
font_icon_material: 1
copyright_text: 1
scrolltotop_on: 1
styling: 0
styling_code: ''
font_icon_fontawesome5: 0
