<?php


use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\File\Entity\File; 

/**
 * Implements hook_help().
 * 
 *  {@inheitdoc}
 */
function rk_customlogin_help($route_name, RouteMatchInterface $route_match){
  switch ($route_name){
    case 'help.page.rk_customlogin':
      $output = '';
      $output.= '<h3>'. t('Settings') .'</h3>';
      return $output;
  } 
}

/**
 * Implements hook_preprocess_html().
 * 
 * {@inheitdoc}
 */
function rk_customlogin_preprocess_html($variables){
   $path = \Drupal::service('path.current')->getpath();
   $user_path = ['/user', '/user/login', '/user/password', '/user/register' ];
   $current_user = \Drupal::currentUser();//gets the current active user
   if($current_user->id()){
     if(in_array($path, $user_path)){

     }
   }
}

  /**
 * Implements hook_theme_suggestions_alter().
 * 
 * {@inheitdoc}
 */
function rk_customlogin_theme_suggestions_alter(array &$suggestions, array $variables, $hook){
    if($hook == 'page'){
        $path = \Drupal::service('path.current')->getpath();
    }
}

/**
 * Implements hook_form_alter().
 * 
 * {@inheitdoc}
 */
function rk_customlogin_form_alter(&$form, FormStateInterface $form_state, $form_id){
    if($form_id == 'user_login_form'){
        $form['#access'] = FALSE;
    }
}

/**
 * Implements hook_element_info_alter().
 * 
 * {@inheitdoc}
 */
function rk_customlogin_element_info_alter(array &$types){
  if(isset($types['password_confirm'])){
    $types['password_confirm']['#process'][] = 'rk_customlogin_password_confirm';
  }
}
/**
 * Process password confirm element
 */
 function rk_customlogin_password_confirm($element){
   $element['pass1']['#title_display'] = 'invisible';
 }
/**
 * Implements hook_page_attachments().
 * 
 * {@inheitdoc}
 */
function rk_customlogin_page_attachments(array &$attachments){
    
}

/**
 * Implements hook_theme_registery_alter().
 * 
 * {@inheitdoc}
 */
function rk_customlogin_theme_registery_alter(&$theme_registry){
  $path = \Drupal::service('module_handler')->getModule('cmacgm_customlogin')->getPath(); 
  $theme = \Drupal::theme()->getActiveTheme();//check if the file exists in the theme directory
  if(file_exists($theme->getpath() .'/templates/rk_customlogin.html.twig')){
    $path = \Drupal::service('theme_handler')->getTheme($theme->getName())->getPath(); 
  }
  $theme_registery['rk_customlogin'] = [
    'preprocess functions' =>[
      0=> 'rk_customlogin_preprocess_simplelogin'
    ],
    'template' => 'rk_customlogin',
    'path' => $path .'/templates',
    'render element' => 'page',
    'type' => 'base_theme_engine'
  ];
}

/**
 * Process rk customlogin
 */
function rk_customlogin_preprocess_simplelogin(&$variables){
  $path = \Drupal::service('path.current')->getpath();
  $variables['#attached']['library'][] = 'rk_customlogin/rk_customlogin-library';
}