_core:
  default_config_hash: 1h6587gjgjkjnmmiuo99Y
access_token_expiration: 8400000
authorization_code_expiration: 8400000
refresh_token_expiration: 1209600
token_cron_batch_size: 0
public_key: 'D:/xampp/key/public.key'
private_key: 'D:/xampp/key/public.key' 
remember_clients: true
use_implicit: false