_core:
  default_config_hash: 1h............Y
access_token_expiration: 8400000
authorization_code_expiration: 8400000
refresh_token_expiration: 1209600
token_cron_batch_size: 0
public_key: /mnt/gfs/onboarding.dev/public.key
private_key: /mnt/gfs/onboarding.dev/private.key 
remember_clients: true
use_implicit: false